import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import '../../core/widgets/civix_widgets.dart';
import '../../core/theme/app_theme.dart';
import '../../data/services/firestore_service.dart';

class ReportScreen extends StatefulWidget{const ReportScreen({super.key});@override State<ReportScreen> createState()=>_ReportScreenState();}
class _ReportScreenState extends State<ReportScreen>{final ctrl=TextEditingController(text:'Gulshan mein flooding ho rahi hai aur roads block hain.');String type='Auto Detect';String loc='Gulshan-e-Iqbal, Karachi';bool loading=false;@override Widget build(BuildContext context)=>GradientShell(child:SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[Text('Report Crisis',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:14),GlassCard(child:Column(children:[DropdownButtonFormField(value:type,items:['Auto Detect','Flood','Fire','Accident','Medical Emergency','Road Block','Violence/Riot','Earthquake','Building Collapse','Electricity Failure','Other'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setState(()=>type=v!),decoration:const InputDecoration(labelText:'Crisis Type')),const SizedBox(height:12),TextField(controller:ctrl,maxLines:5,decoration:const InputDecoration(labelText:'Describe what is happening')),const SizedBox(height:12),TextField(controller:TextEditingController(text:loc),onChanged:(v)=>loc=v,decoration:const InputDecoration(labelText:'Location')),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:(){},icon:const Icon(Icons.image),label:const Text('Image'))),const SizedBox(width:10),Expanded(child:OutlinedButton.icon(onPressed:(){},icon:const Icon(Icons.mic),label:const Text('Voice')))]),const SizedBox(height:18),NeonButton(label:loading?'Analyzing...':'Submit to CIVIX AI',icon:Icons.hub,onTap:loading?(){}:() async{setState(()=>loading=true);final id=await context.read<FirestoreService>().submitReport(ctrl.text,type,loc);if(context.mounted){setState(()=>loading=false);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Report submitted. Multi-agent analysis started.')));context.push('/reasoning/$id');}})])),const SizedBox(height:16),const GlassCard(child:Text('Your report will be written to Firestore in real time. Agent results, alerts, and simulation results are generated as live database records for the MVP demo.',style:TextStyle(color:CivixColors.muted))) ])));}
