import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/widgets/civix_widgets.dart';
import '../../core/theme/app_theme.dart';
import '../../data/models/models.dart';
import '../../data/services/firestore_service.dart';

class LiveMapScreen extends StatelessWidget{const LiveMapScreen({super.key});@override Widget build(BuildContext context)=>GradientShell(child:SafeArea(child:StreamBuilder<List<CrisisReport>>(stream:context.read<FirestoreService>().crises(),builder:(c,s){final crises=s.data??[];return Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Text('Live Crisis Map',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const Spacer(),const StatusPill('REALTIME',CivixColors.green)])),Expanded(child:Padding(padding:const EdgeInsets.all(16),child:GlassCard(padding:EdgeInsets.zero,child:Stack(children:[Container(decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(colors:[Color(0xFF081831),Color(0xFF0C1026)]))),...List.generate(8,(i)=>Positioned(left:20+i*43,top:80+(i%4)*80,child:Container(width:160,height:2,color:CivixColors.cyan.withOpacity(.16)))),...List.generate(7,(i)=>Positioned(top:40+i*65,left:30+(i%2)*70,child:Container(width:2,height:160,color:CivixColors.cyan.withOpacity(.12)))),if(crises.isNotEmpty)...crises.take(6).map((e){final idx=crises.indexOf(e);return Positioned(left:50.0+(idx*43)%250,top:90.0+(idx*71)%420,child:_Marker(e:e));}),Positioned(left:72,top:120,child:Container(width:190,height:190,decoration:BoxDecoration(shape:BoxShape.circle,color:CivixColors.cyan.withOpacity(.08),border:Border.all(color:CivixColors.cyan.withOpacity(.3))))),Positioned(right:16,bottom:16,left:16,child:GlassCard(child:crises.isEmpty?const Text('Seed Firestore to see live crises on map.'):Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(crises.first.title,style:const TextStyle(fontWeight:FontWeight.w900)),Text('${crises.first.locationName} • Radius ${crises.first.affectedRadiusKm}km'),const SizedBox(height:8),Wrap(spacing:8,children:[StatusPill(crises.first.severity,CivixColors.orange),StatusPill('${crises.first.confidence.toInt()}% AI',CivixColors.cyan),const StatusPill('ETA 9 min',CivixColors.green)])])))]))))] );}))));}
class _Marker extends StatelessWidget{final CrisisReport e;const _Marker({required this.e});@override Widget build(BuildContext context)=>Column(children:[Icon(e.type.contains('Fire')?Icons.local_fire_department:e.type.contains('Medical')?Icons.local_hospital:Icons.flood,color:e.severity=='CRITICAL'?CivixColors.red:CivixColors.orange,size:34),Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(12)),child:Text(e.locationName.split(',').first,style:const TextStyle(fontSize:10)))]);}
