import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/widgets/civix_widgets.dart';
import '../../core/theme/app_theme.dart';
import '../../data/models/models.dart';
import '../../data/services/firestore_service.dart';

class AnalyticsScreen extends StatelessWidget{const AnalyticsScreen({super.key});@override Widget build(BuildContext context)=>GradientShell(child:Scaffold(appBar:AppBar(title:const Text('Analytics Dashboard'),backgroundColor:Colors.transparent),body:StreamBuilder<List<CrisisReport>>(stream:context.read<FirestoreService>().crises(),builder:(c,s){final crises=s.data??[];final active=crises.where((e)=>e.status!='Resolved').length;return ListView(padding:const EdgeInsets.all(16),children:[GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),mainAxisSpacing:12,crossAxisSpacing:12,childAspectRatio:1.3,children:[_kpi('Active Cases','$active',CivixColors.red),_kpi('Avg AI Confidence',crises.isEmpty?'0%':'${(crises.map((e)=>e.confidence).reduce((a,b)=>a+b)/crises.length).toStringAsFixed(0)}%',CivixColors.cyan),_kpi('People At Risk','${crises.fold<int>(0,(a,b)=>a+b.peopleAtRisk)}',CivixColors.orange),_kpi('Blocked Roads','${crises.fold<int>(0,(a,b)=>a+b.blockedRoads)}',CivixColors.purple)]),const SizedBox(height:16),GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Crisis Distribution',style:TextStyle(fontWeight:FontWeight.w900)),SizedBox(height:220,child:PieChart(PieChartData(sections:[PieChartSectionData(value:35,title:'Flood'),PieChartSectionData(value:25,title:'Traffic'),PieChartSectionData(value:15,title:'Medical'),PieChartSectionData(value:10,title:'Fire'),PieChartSectionData(value:10,title:'Infra'),PieChartSectionData(value:5,title:'Other')])))])),const SizedBox(height:16),const GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('High Risk Areas',style:TextStyle(fontWeight:FontWeight.w900)),SizedBox(height:8),Text('1. Gulshan-e-Iqbal\n2. Saddar\n3. Shahrah-e-Faisal\n4. North Nazimabad\n5. Korangi',style:TextStyle(color:CivixColors.muted))]))]);}))));}
Widget _kpi(String t,String v,Color c)=>GlassCard(glow:c,child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(v,style:TextStyle(color:c,fontSize:24,fontWeight:FontWeight.w900)),Text(t,style:const TextStyle(color:CivixColors.muted))]));
