import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/widgets/civix_widgets.dart';
import '../../core/theme/app_theme.dart';
import '../../data/models/models.dart';
import '../../data/services/firestore_service.dart';

class SimulationScreen extends StatelessWidget{final String crisisId;const SimulationScreen({super.key,required this.crisisId});@override Widget build(BuildContext context)=>GradientShell(child:Scaffold(appBar:AppBar(title:const Text('Emergency Simulation'),backgroundColor:Colors.transparent),body:StreamBuilder<SimulationResult?>(stream:context.read<FirestoreService>().simulation(crisisId),builder:(c,s){final r=s.data;if(r==null)return const Center(child:Text('No simulation result found yet.'));return ListView(padding:const EdgeInsets.all(16),children:[Row(children:[Expanded(child:_box('Before AI','${r.beforeCongestion}% congestion','${r.beforeEta} min ETA',CivixColors.red)),const SizedBox(width:12),Expanded(child:_box('After AI','${r.afterCongestion}% congestion','${r.afterEta} min ETA',CivixColors.green))]),const SizedBox(height:16),_impact('Traffic congestion reduced','${r.congestionReduction.toInt()}%',CivixColors.cyan),_impact('Emergency ETA improved','${r.etaImprovement.toInt()}%',CivixColors.green),_impact('Rescue coverage improved','${r.rescueCoverageImprovement.toInt()}%',CivixColors.purple),_impact('People alerted','${r.peopleAlerted}',CivixColors.orange),const SizedBox(height:16),const GlassCard(child:Text('Simulation shows optimized traffic rerouting, ambulance movement, rescue team deployment, police control points, and citizen alert coverage.',style:TextStyle(color:CivixColors.muted)))]);})));}
Widget _box(String t,String a,String b,Color color)=>GlassCard(glow:color,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:TextStyle(color:color,fontWeight:FontWeight.w900)),const SizedBox(height:14),Text(a,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800)),Text(b,style:const TextStyle(color:CivixColors.muted))]));
Widget _impact(String t,String v,Color color)=>Padding(padding:const EdgeInsets.only(bottom:12),child:GlassCard(glow:color,child:Row(children:[Expanded(child:Text(t)),Text(v,style:TextStyle(color:color,fontSize:24,fontWeight:FontWeight.w900))])));
